## baseurl has to be without cv/ when generating pdf
## so use https://cssandstuff.github.io/ instead

baseurl = "https://cssandstuff.github.io/cv"
disableKinds = ["RSS"]
defaultContentLanguage = "en"
enableRobotsTXT = true
languageCode = "en-us"
theme = "winning"
title = "CV Tim Clulow"
[taxonomies]
[markup.goldmark.renderer]
unsafe= true